version: '2'
services:

  # Data
  dbdata:
    image: busybox
    command: "true"
    volumes:
      - /var/lib/postgresql/data
      - /data

  db:
    image: postgres:9.6
    ports:
      - "5432:5432"
    volumes_from:
      - dbdata

  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    volumes_from:
      - web
    links:
      - web:web

  web:
    build:
      context: ./server/
    volumes:
      - ./logs:/var/app/logs
      - ./server:/var/app
      - ./staticfiles:/www/static
    ports:
      - "5000:8080"
    links:
      - db:db
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.docker
      - DJANGO_ENV_FILE=.docker.env
      - DJANGO_SECRET_KEY=stage-dummy-key1
      - RDS_DB_NAME=postgres
      - RDS_USERNAME=postgres
      - RDS_PASSWORD=''
      - RDS_HOSTNAME=db
      - RDS_PORT=5432
      - DATABASE_URL=postgres://postgres@db/postgres

